version: '3.7'

services:
  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      environment:
        RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: admin
        RABBITMQ_DEFAULT_VHOST: "/"
      ports:
        - 5672:5672
        - 15672:15672